services:
  - type: static
    name: chefcode-landing
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
